version: '3.5'

services:
    jibri:
        build:
            context: .
        restart: always
        volumes:
            - ./recordings:/recordings
            - /dev/shm:/dev/shm
        cap_add:
            - SYS_ADMIN
            - NET_BIND_SERVICE
        devices:
            - /dev/snd:/dev/snd
        env_file:
             - .env

